### ISSUE TITLE
Display virtual operations

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos-explorer#15]

**Comment by epexa** [comment]
в этом нет необходимости, подробно смотрите #2 и #3

**Comment by epexa** [comment]
всё-таки можно добавить виртуальные опреции в фильтр

**Comment by epexa** [comment]
добавил 9 виртуальных методов 2f058667d31677b98c5ed559ad207e2485ed4d6a

**Comment by marijadia** [comment]
Доработать подробный вывод по виртуальным операциям. Сейчас они показываются как куча нолей и не выводят необходимую информацию - объем трансферов системы.
