### ISSUE TITLE
делегаты

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos-explorer#31]
вывести таблицу делегатов

**Comment by epexa** [comment]
https://explorer.golos.io/#witnesses

![witnesses](https://user-images.githubusercontent.com/2198826/39551753-f8e63b20-4e6e-11e8-9b3e-7a0b7179026e.png)

**Comment by marijadia** [comment]
![image](https://user-images.githubusercontent.com/30824714/39552363-8ea06c10-4e71-11e8-9e87-a5be89178a7f.png)
добавить правила font-size: 14px;
    color: #888;
    font-family: verdana;
для ссылки на пост
