### ISSUE TITLE
сделать API

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos-explorer#35]
сделать API (json)

**Comment by epexa** [comment]
**для решения задач #32 и #33 понадобилось сделать API.
репозиторий бекенда находится здесь: https://github.com/GolosChain/golos-explorer-api
теперь считаю разумным описать эти 2 метода на отдельной новой странице в эксплорере и сделать там песочницу.**

**Comment by epexa** [comment]
**описание API готово:
https://explorer.golos.io/#api**

![golosexplorer 2](https://user-images.githubusercontent.com/2198826/44462831-7fe8e800-a61e-11e8-91ac-4705e7dbe3cb.png)

**сделано при помощи SwaggerHub, редактировать можно здесь:
https://app.swaggerhub.com/apis/goloschain/explorer/1.0.0**

**Comment by afalaleev** [comment]
Не получается задать условия фильтрации и сортировки

![image](https://user-images.githubusercontent.com/27198658/44507108-8be2b180-a6d3-11e8-9165-c13fd289e99c.png)

Условие задается но не работает.

**Comment by epexa** [comment]
**да, API работает отлично, однако есть такой нюанс:
в SwaggerHub нужно описать подробно эти параметры, у них сложная структура и поэтому прямо через Swagger песочницу не удаётся правильно указать значения.**

**для filterModel:**
https://api-explorer.golos.io/getAccounts?filterModel[name][type]=contains&filterModel[name][filter]=goloscore&filterModel[name][filterType]=text

**для sortModel:**
https://api-explorer.golos.io/getAccounts?sortModel[0][colId]=post_count&sortModel[0][sort]=desc

**Comment by afalaleev** [comment]
Надо выделить в отдельную задачу. А эту закрыть.

**Comment by epexa** [comment]
> Надо выделить в отдельную задачу. А эту закрыть.

@afalaleev сделал: #75
