### ISSUE TITLE
логотип, favicon, мета-теги, op мета-теги

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos-explorer#40]
добавить:
- [x] логотип в навбар (меню)
- [x] favicon
- [x] мета-теги (title, keywords, description)
- [x] Open Graph мета-теги

**Comment by epexa** [comment]
требуется выполнение задачи #42

**Comment by epexa** [comment]
**telegram:**
![telegram](https://user-images.githubusercontent.com/2198826/44465260-bd04a880-a625-11e8-8e72-28b9f38a225d.png)
**vkontakte:**
![vk](https://user-images.githubusercontent.com/2198826/44465267-c2fa8980-a625-11e8-8ff6-023dbf18c67f.png)
**vkontakte wall:**
![vk_wall](https://user-images.githubusercontent.com/2198826/44465273-c8f06a80-a625-11e8-8fad-d0acaeb98d34.png)
**twitter:**
![twitter](https://user-images.githubusercontent.com/2198826/44465282-cd1c8800-a625-11e8-99c8-36097a9e2158.png)
**facebook:**
![fb](https://user-images.githubusercontent.com/2198826/44465296-d4439600-a625-11e8-8ea8-ae28ef94af61.png)
**facebook wall:**
![fb_wall](https://user-images.githubusercontent.com/2198826/44465302-d9084a00-a625-11e8-8a0f-f142a24020b6.png)

**Comment by marijadia** [comment]
супер
