### ISSUE TITLE
логотип

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos-explorer#42]
_Для сервиса [Explorer](https://explorer.golos.io) нужно сделать логотип._

Идеи:
1. Сделать GolosExplorer - где две буквы "о" в слове gOlOs в виде бинокля. Пример бинокля см. файл: binoculars.png. А слово Explorer зделать слитно в стиле см. файл: example2.gif;
2. Сделать с лупой, например буква "E" находится в ней (GolosExplorer). Или как см. файл: example3.gif. Только вместо круга, "xplorer" взято в лупу;
3. Сделать в виде двоичной системы, где вместо букы "о" - 0 (ноль), а вместо "l" - 1 (единица): g010s(Exp)10rer.

_Golos и Explorer можно выделить разными цветами в стиле голоса (красный и синий)._

**Логотип должен быть сделан в векторе.**

**Так же ещё должен быть вариант логотипа квадратноо формата (1х1).**

_Можно также придумать что-нибудь связаное с плюсами, так как блокчейн Голос написан на С++_.

В прикрепленом архиве так же есть логотип Голоса в векторе, см. файл: golos_logo.svg.

[GolosExplorer Logo.zip](https://github.com/GolosChain/golos-explorer/files/1963974/GolosExplorer.Logo.zip)

**Comment by epexa** [comment]
исполнитель @kuchinskaya

**Comment by kuchinskaya** [comment]
![golos_explorer_3](https://user-images.githubusercontent.com/37017857/39583922-dc1ee826-4ef9-11e8-9a1a-8285dafd7751.png)
![golos_explorer_6](https://user-images.githubusercontent.com/37017857/39583923-dc41535c-4ef9-11e8-84b3-da2fe2af5bd1.png)
![golos_explorer_7](https://user-images.githubusercontent.com/37017857/39583924-dc5dc730-4ef9-11e8-8ff2-3b9f1f1e21eb.png)

**Comment by marijadia** [comment]
![image](https://user-images.githubusercontent.com/30824714/39636891-2eaa5c26-4fca-11e8-965d-7d7f78135ca5.png)
Мне больше всего этот вариант нравится. Давай остановимся на нем. только там неровно немного.

**Comment by kuchinskaya** [comment]
[svg.zip](https://github.com/GolosChain/golos-explorer/files/1979275/svg.zip)

**Comment by epexa** [comment]
![logo](https://user-images.githubusercontent.com/2198826/39766527-320b40da-52ed-11e8-8af5-eb68ab89952d.png)
