### ISSUE TITLE
Баги в работе пагинации

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos-explorer#47]
- [x] 1. когда кликаю по случайному номеру страницы в пагинации, то все номера после этого пропадают из пагинации.
- [x] 2. например, на странице https://explorer.golos.io/#account/vik/39/ есть операции которые выводятся с полным контентом (можно увидеть в конце страницы). Мы должны видеть операции только в одну строку.

**Comment by epexa** [comment]
**второй пункт решен этим ишью:** #50
