### ISSUE TITLE
Контент растягивает таблицу

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos-explorer#49]
- [x] Необходимо убрать из таблицы  Title: Body: , Мемо

- [x] Permlink  и Parent permlink сделать ссылками

Иначе большие данные растягивают таблицу
![image](https://user-images.githubusercontent.com/30824714/41606440-5e91d82e-73ec-11e8-9f3d-02b370f55ca2.png)

**Comment by epexa** [comment]
**теперь контент не вылазит за ширину страницы:**
![account](https://user-images.githubusercontent.com/2198826/41642469-11424fce-7471-11e8-8141-a0456af91060.png)

**Comment by epexa** [comment]
"Необходимо убрать из таблицы Title: Body: , Мемо" **нужно ли теперь это убирать или лучше оставить? можно сделать чтобы большие строки просто сворачивались.**

**Comment by epexa** [comment]
"Permlink и Parent permlink сделать ссылками" **ссылками на что?**
