### ISSUE TITLE
ресерч: интегрирация с Shiny Server

### ISSUE THREAD

**Issue by epexa** [GolosChain/golos-explorer#61]
чтобы связать аналитику которая сделана через Shiny Server, нужно провести ресерч, как интегрировать Shiny Server с эксплорером.

**Comment by epexa** [comment]
**используется следующее ПО:
https://github.com/rstudio/shiny-server
https://github.com/rocker-org/shiny
https://github.com/rstudio/shinydashboard**

**Comment by epexa** [comment]
**просмотрел все репы rstudio, есть несколько которых нужно изучить подробнее:
https://github.com/rstudio/rstudioapi
https://github.com/rstudio/rsconnect
https://github.com/rstudio/shiny-server-client
https://github.com/rstudio/pool
https://github.com/rstudio/webdriver**

**Comment by marijadia** [comment]
Нужно попробовать изучить и настроить api для связки репортинга и экплорера

**Comment by epexa** [comment]
**вывод:
есть возможность [переделать R скрипты так, чтобы Shiny Server отдавал JSON](https://stackoverflow.com/questions/25297489/accept-http-request-in-r-shiny-application#25297636), т.е работал как HTTP API. однако использование Shiny Server как публичный HTTP API @muhazzz считает не очень, т.к. считает данное ПО не предназначено для публичного сервиса.
поэтому пришли к решению, что R скрипты будут по крону сохранять JSON в файлы, далее Nginx будет отдавать их (с кэшированием), а эксплорер будет обращаться к этим файлам. поэтому следующая задача - это интегрирация готового графика (который генерирует [Shiny Dashbord](https://github.com/rstudio/shinydashboard)) с готовыми данными (который генерирует [Shiny Server](https://github.com/rstudio/shiny-server)) в эксплорер, и разработка архитектуры в эксплорере так, чтобы можно было легко интегрировать новые готовые графики.
_P.S. вообще я считаю, что всю аналитику и статистику нужно писать на NodeJS, в [существующем бекенде для эксплорера](https://github.com/GolosChain/golos-explorer-api)._**

**Comment by epexa** [comment]
**#66 следующая задача**
