### ISSUE TITLE
Integrate the first chart of report 

### ISSUE THREAD

**Issue by marijadia** [GolosChain/golos-explorer#66]
Take the json file of the first post's chart of report system and try to integrate it in explorer.

**Comment by epexa** [comment]
**получилось интегрировать готовый график с [Shiny Dashbord](https://github.com/rstudio/shinydashboard) и данные с [Shiny Server](https://github.com/rstudio/shiny-server).
посмотреть можно здесь: https://explorer.golos.io/#analytics/comments**
![golosexplorer 3](https://user-images.githubusercontent.com/2198826/43525681-26d5c932-95ab-11e8-91fe-602964bbe159.png)

**Comment by epexa** [comment]
**однако есть 3 проблемы:**
- [ ] **в сгенерировнном графике есть много нерабочих кнопок, так как для их работы нужен бекенд, но эти кнопки являются необязательными, поэтому их нужно убрать;**
- [ ] **в сгенерированом js-коде очень много лишнего кода, нужно его почитстить;**
- [ ] **для работы сгенерированного js-кода используется jQuery, необходимо по возможности избавиться от него.**
